pipeline {
    agent any
    
    tools {nodejs "NodeJS"}

    stages {

        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }

        stage("Clone Repo"){
            steps{
                // Replace bat with sh if running the Jeknins server on Linux
                bat "git clone https://github.com/AmarjeetYelwande/AutomationTestingOnline.git"                
            }       
        }       

        stage('Install Dependencies') {
            steps{
                dir("automationtestingonline"){   
                    // Replace bat with sh if running the Jeknins server on Linux                 
                    bat 'npm ci'                                              
                    bat 'npx playwright install --with-deps'                    
                }
            }           
        }

        stage('Run Tests') {
            steps{

            dir("automationtestingonline"){
                // Replace bat with sh if running the Jeknins server on Linux
                bat 'npm run test'
                }            
            }
        }
    }


    post {
        always {
            archiveArtifacts artifacts: 'playwright-report/**', allowEmptyArchive: true
        }
        failure {
            echo 'Tests failed! Check the report.'
        }
    }
}